
all:
	go build

t1:
	go get "github.com/go-playground/mold"
	go get "github.com/gin-gonic/gin"

# To Use
#		// var Validator StructValidator = &defaultValidator{}
#		binding.Validator = &customValidator.CustomValidator{}
